name: GitHub Tetris

on:
  schedule:
    - cron: "*/30 * * * *"   # every 30 minutes
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Generate Tetris SVG
        run: python tetris/generate_tetris.py

      - name: Commit SVG
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add tetris/tetris.svg
          git commit -m "Update GitHub Tetris" || exit 0
          git push
